# Default configuration for Medical Image Captioning Pipeline
# This config supports ViT-GPT2 baseline with extensible architecture

# Dataset Configuration
dataset:
  name: "indiana_chest_xray"
  data_dir: "/kaggle/input/chest-xrays-indiana-university"
  image_dir: "images/images_normalized"
  reports_file: "indiana_reports.csv"
  projections_file: "indiana_projections.csv"
  train_split: 0.8
  val_split: 0.1
  test_split: 0.1
  max_caption_length: 128
  image_size: [224, 224]

# Data Preprocessing
preprocessing:
  text_normalization: true
  lowercase: true
  remove_special_chars: true
  normalize_whitespace: true

# Model Configuration
model:
  name: "ViT-GPT2"
  encoder:
    type: "vit"
    model_name: "google/vit-base-patch16-224"
    freeze_encoder: false
    projection_dim: null  # null means no projection needed
  
  decoder:
    type: "gpt2"
    model_name: "gpt2"
    add_cross_attention: true
    freeze_decoder: false

# Training Configuration
training:
  batch_size: 16
  num_epochs: 5
  learning_rate: 5e-5
  weight_decay: 0.01
  warmup_steps: 100
  gradient_clip_norm: 1.0
  log_steps: 20
  save_steps: 500
  eval_steps: 100

# Generation Configuration
generation:
  max_length: 100
  top_p: 0.9
  temperature: 1.0
  do_sample: true
  num_beams: 1

# Evaluation Configuration
evaluation:
  metrics: ["bleu1", "bleu4", "meteor", "rouge_l", "bert_score"]
  num_samples: 200
  bert_score_lang: "en"

# System Configuration
system:
  device: "auto"  # auto, cuda, cpu
  num_workers: 4
  seed: 42
  mixed_precision: false

# Logging and Checkpointing
logging:
  log_dir: "logs"
  checkpoint_dir: "checkpoints"
  save_best_model: true
  save_last_model: true
  tensorboard: true

# Paths
paths:
  output_dir: "outputs"
  model_save_path: "models"
  results_save_path: "results"
